---
abstract: 'guess C++ compiler and flags'
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
  - 'Steffen Mueller <smueller@cpan.org>'
  - 'Tobias Leich <froggs@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  ExtUtils::Manifest: '0'
  Fatal: '0'
  File::Spec: '0'
  Module::Build: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ExtUtils-CppGuess
provides:
  ExtUtils::CppGuess:
    file: lib/ExtUtils/CppGuess.pm
    version: '0.08'
requires:
  Capture::Tiny: '0'
  File::Basename: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tsee/extutils-cppguess
version: '0.08'
